### ISSUE TITLE
[BUG]: Missing configuration for Grafana container

### ISSUE THREAD

**Issue by FengJi2021** [NVIDIA-AI-Blueprints/rag#19]
### Version

lastest

### Describe the bug.

Hi BP Team,
The docker compose in the current version has no configuration files with it.
After deployment, there is no dashboard showing.

```yaml
  grafana:
    container_name: grafana-service
    image: grafana/grafana
    ports:
      - "3000:3000"
```

### Minimum reproducible example

```shell
...
```

### Relevant log output

```shell
...
```

### Full env printout

```shell
...
```

### Code of Conduct

- [x] I agree to follow __THIS PROJECT__'s Code of Conduct
- [x] I have searched the [open bugs](https://github.com/NVIDIA-AI-Blueprints/rag/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report
